### ISSUE TITLE
how to start genieacs-sim without error

### ISSUE THREAD

**Issue by raulllima** [genieacs/genieacs-sim#13]
root@fqdn:~/genieacs-sim# ./genieacs-sim
Simulator 000000 started
/root/genieacs-sim/simulator.js:288
    if (err) throw err;
             ^

Error: connect ECONNREFUSED 127.0.0.1:7547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7547
}
Simulator 000000 died (1). Restarting in 10 seconds...
^C

**Comment by ncux85** [comment]
# ./genieacs-sim -u http://localhost:80
Simulator 000000 started
/genieacs-sim/xml-utils.js:3
function node(key, attrs = {}, value = "") {
                         ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wariator/genieacs-sim/simulator.js:5:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
Simulator 000000 died (1). Restarting in 10 seconds...

**Comment by masonwu65** [comment]
Hi Sir,

I guess your genieacs and genieacs-sim are not the same PC and you have to use http://genieas_server_IP:7547 instead.

**Comment by vagkaefer** [comment]
The simulator is trying to connect to the ACS server at 127.0.0.1:7547 and is not succeeding.

Is your ACS on localhost and on this port? Check the parameters.

Use the --help option to see the parameters.
