### ISSUE TITLE
Help Needed - Getting startup error - TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by Sainih5** [genieacs/genieacs-sim#14]
Simulator 000000 started
Simulator 000000 listening for connection requests on http://10.10.1.250:42333/
/root/genieacs-sim/xml-utils.js:6
  for (const [k, v] of Object.entries(attrs)) attrsStr += ` ${k}="${v}"`;
                              ^

TypeError: Object.entries is not a function
    at Object.node (/root/genieacs-sim/xml-utils.js:6:31)
    at Object.inform (/root/genieacs-sim/methods.js:31:29)
    at startSession (/root/genieacs-sim/simulator.js:109:11)
    at listenForConnectionRequests (/root/genieacs-sim/simulator.js:294:5)
    at Server.httpServer.listen.err (/root/genieacs-sim/simulator.js:256:14)
    at Server.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1297:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
Simulator 000000 died (1). Restarting in 10 seconds...

**Comment by Sainih5** [comment]
Issue resolved on re-installation.
