### ISSUE TITLE
I get this error whenever i start ./genieacs-sim

### ISSUE THREAD

**Issue by Nirmeen23** [genieacs/genieacs-sim#23]
/home/ubuntu/genieacs-sim/simulator.js:288
    if (err) throw err;
             ^

Error: connect ECONNREFUSED 127.0.0.1:7547
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
Simulator 000000 died (1). Restarting in 10 seconds...

**Comment by vagkaefer** [comment]
The simulator is trying to connect to the ACS server at 127.0.0.1:7547 and is not succeeding.

Is your ACS on localhost and on this port? Check the parameters.

Use the --help option to see the parameters.
